events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            # This line forwards traffic to the sample web application inside Docker.
            # If your application runs outside of Docker on your main computer, change "webapp:8080" to "host.docker.internal:YOUR_PORT".
            proxy_pass http://host.docker.internal:1234;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
